parameters:
    boa.permissions:
        BUSINESS_MANAGE_CONFIGURATION:
            label: Administrer la configuration
            description: Administrer la configuration.

        BUSINESS_MANAGE_CALENDARS:
            label: Administrer les calendriers
            description: Administrer les calendriers.

        BUSINESS_MANAGE_ROUTES:
            label: Gerer les routes
            description: Gerer les routes