parameters:
    boa.permissions:
        BUSINESS_MANAGE_CONFIGURATION:
            label: Administrer la configuration
            description: Administrer la configuration

        BUSINESS_VIEW_CONFIGURATION:
            label: Consulter la configuration
            description: Consulter la configuration

        BUSINESS_MANAGE_CALENDARS:
            label: Administrer les calendriers
            description: Administrer les calendriers

        BUSINESS_VIEW_CALENDARS:
            label: Consulter les calendriers
            description: Consulter les calendriers

        BUSINESS_MANAGE_ROUTES:
            label: Administrer les routes
            description: Administrer les routes

        BUSINESS_VIEW_ROUTES:
            label: Consulter les routes
            description: Consulter les routes

        BUSINESS_MANAGE_STOPS:
            label: Administrer les arrêts
            description: Administrer les arrêts

        BUSINESS_VIEW_STOPS:
            label: Consulter les arrêts
            description: Consulter les arrêts

        BUSINESS_VIEW_MONITORING:
            label: Contrôler les données
            description: Contrôler les données
