tisseo_boa_homepage:
    pattern:  /{externalNetworkId}
    defaults: { _controller: TisseoBOABundle:Default:index , externalNetworkId: null}

tisseo_boa_accessibility_mode_list:
    pattern: /accessibility_mode/list
    defaults: { _controller: TisseoBOABundle:AccessibilityMode:list }
tisseo_boa_accessibility_mode_edit:
    pattern: /accessibility_mode/edit/{AccessibilityModeId}
    defaults: { _controller: TisseoBOABundle:AccessibilityMode:edit, AccessibilityModeId: null }

tisseo_boa_agency_list:
    pattern: /agency/list
    defaults: { _controller: TisseoBOABundle:Agency:list }
tisseo_boa_agency_edit:
    pattern: /agency/edit/{AgencyId}
    defaults: { _controller: TisseoBOABundle:Agency:edit, AgencyId: null }

tisseo_boa_color_list:
    pattern: /color/list
    defaults: { _controller: TisseoBOABundle:Color:list }
tisseo_boa_color_edit:
    pattern: /color/edit/{ColorId}
    defaults: { _controller: TisseoBOABundle:Color:edit, ColorId: null }

tisseo_boa_datasource_list:
    pattern: /datasource/list
    defaults: { _controller: TisseoBOABundle:Datasource:list }
tisseo_boa_datasource_edit:
    pattern: /datasource/edit/{DatasourceId}
    defaults: { _controller: TisseoBOABundle:Datasource:edit, DatasourceId: null }

tisseo_boa_exception_type_list:
    pattern: /exception_type/list
    defaults: { _controller: TisseoBOABundle:ExceptionType:list }
tisseo_boa_exception_type_edit:
    pattern: /exception_type/edit/{ExceptionTypeId}
    defaults: { _controller: TisseoBOABundle:ExceptionType:edit, ExceptionTypeId: null }

tisseo_boa_log_list:
    pattern: /log/list
    defaults: { _controller: TisseoBOABundle:Log:list }
tisseo_boa_log_edit:
    pattern: /log/edit/{LogId}
    defaults: { _controller: TisseoBOABundle:Log:edit, LogId: null }

tisseo_boa_physical_mode_list:
    pattern: /physical_mode/list
    defaults: { _controller: TisseoBOABundle:PhysicalMode:list }
tisseo_boa_physical_mode_edit:
    pattern: /physical_mode/edit/{PhysicalModeId}
    defaults: { _controller: TisseoBOABundle:PhysicalMode:edit, PhysicalModeId: null }

tisseo_boa_poi_type_list:
    pattern: /poi_type/list
    defaults: { _controller: TisseoBOABundle:PoiType:list }
tisseo_boa_poi_type_edit:
    pattern: /poi_type/edit/{PoiTypeId}
    defaults: { _controller: TisseoBOABundle:PoiType:edit, PoiTypeId: null }

