tisseo_boa_homepage:
    pattern:  /{externalNetworkId}
    defaults: { _controller: TisseoBoaBundle:Default:index , externalNetworkId: null}

#Accessibility administration
tisseo_boa_accessibility_mode_list:
    pattern: /accessibility_mode/list
    defaults: { _controller: TisseoBoaBundle:AccessibilityMode:list }
tisseo_boa_accessibility_mode_edit:
    pattern: /accessibility_mode/edit/{accessibilityModeId}
    defaults: { _controller: TisseoBoaBundle:AccessibilityMode:edit, accessibilityModeId: null }

#Agencies administration
tisseo_boa_agency_list:
    pattern: /agency/list
    defaults: { _controller: TisseoBoaBundle:Agency:list }
tisseo_boa_agency_edit:
    pattern: /agency/edit/{agencyId}
    defaults: { _controller: TisseoBoaBundle:Agency:edit, agencyId: null }

#Calendars administration
tisseo_boa_calendar_list:
    pattern: /calendar/list/{calendarType}
    defaults: { _controller: TisseoBoaBundle:Calendar:list, calendarType: null }
tisseo_boa_calendar_edit:
    pattern: /calendar/edit/{calendarId}
    defaults: { _controller: TisseoBoaBundle:Calendar:edit, calendarId: null }
tisseo_boa_calendar_delete:
    pattern:  /calendar/delete/{calendarId}/{calendarType}
    defaults: { _controller: TisseoBoaBundle:Calendar:delete}

#Calendar elements administration
tisseo_boa_calendar_element_list:
    pattern: /calendar_element/list/{Calendar}
    defaults: { _controller: TisseoBoaBundle:CalendarElement:list, Calendar: null }
tisseo_boa_calendar_element_edit:
    pattern: /calendar_element/edit/{CalendarElementId}
    defaults: { _controller: TisseoBoaBundle:CalendarElement:edit, calendarId: null }

#Color administration
tisseo_boa_color_list:
    pattern: /color/list
    defaults: { _controller: TisseoBoaBundle:Color:list }
tisseo_boa_color_edit:
    pattern: /color/edit/{colorId}
    defaults: { _controller: TisseoBoaBundle:Color:edit, colorId: null }

#Data sources administration
tisseo_boa_datasource_list:
    pattern: /datasource/list
    defaults: { _controller: TisseoBoaBundle:Datasource:list }
tisseo_boa_datasource_edit:
    pattern: /datasource/edit/{datasourceId}
    defaults: { _controller: TisseoBoaBundle:Datasource:edit, datasourceId: null }

#Exception types administration
tisseo_boa_exception_type_list:
    pattern: /exception_type/list
    defaults: { _controller: TisseoBoaBundle:ExceptionType:list }
tisseo_boa_exception_type_edit:
    pattern: /exception_type/edit/{exceptionTypeId}
    defaults: { _controller: TisseoBoaBundle:ExceptionType:edit, exceptionTypeId: null }

#Property administration
tisseo_boa_property_list:
    pattern: /property/list
    defaults: { _controller: TisseoBoaBundle:Property:list }
tisseo_boa_property_edit:
    pattern: /property/edit/{propertyId}
    defaults: { _controller: TisseoBoaBundle:Property:edit, propertyId: null }

#Log administration
tisseo_boa_log_list:
    pattern: /log/list
    defaults: { _controller: TisseoBoaBundle:Log:list }
tisseo_boa_log_edit:
    pattern: /log/edit/{logId}
    defaults: { _controller: TisseoBoaBundle:Log:edit, logId: null }

#Physical mode administration
tisseo_boa_physical_mode_list:
    pattern: /physical_mode/list
    defaults: { _controller: TisseoBoaBundle:PhysicalMode:list }
tisseo_boa_physical_mode_edit:
    pattern: /physical_mode/edit/{physicalModeId}
    defaults: { _controller: TisseoBoaBundle:PhysicalMode:edit, physicalModeId: null }

#POI administration
tisseo_boa_poi_type_list:
    pattern: /poi_type/list
    defaults: { _controller: TisseoBoaBundle:PoiType:list }
tisseo_boa_poi_type_edit:
    pattern: /poi_type/edit/{poiTypeId}
    defaults: { _controller: TisseoBoaBundle:PoiType:edit, poiTypeId: null }

#ajax calls
tisseo_boa_json_calendars:
    pattern: /json/calendars/{calendarType}
    defaults: { _controller: "TisseoBoaBundle:Json:calendars", calendarType: null}
tisseo_boa_json_bitmask:
    pattern: /json/bitmask
    defaults: { _controller: "TisseoBoaBundle:Json:bitmask"}
tisseo_boa_json_service_calendar_bitmask:
    pattern: /json/service/calendar/bitmask
    defaults: { _controller: "TisseoBoaBundle:Json:ServiceCalendarBitmask"}
tisseo_boa_json_stop:
    pattern: /json/stop
    defaults: { _controller: "TisseoBoaBundle:Json:stop"}
    options:
        expose: true
tisseo_boa_json_stop_area:
    pattern: /json/stop_area
    defaults: { _controller: "TisseoBoaBundle:Json:stopArea"}
tisseo_boa_json_city:
    pattern: /json/city
    defaults: { _controller: "TisseoBoaBundle:Json:city"}
tisseo_boa_json_internal_transfer:
    pattern: /json/internal_transfer
    defaults: { _controller: "TisseoBoaBundle:Json:internalTransfer"}
    options:
        expose: true
tisseo_boa_json_external_transfer:
    pattern: /json/external_transfer
    defaults: { _controller: "TisseoBoaBundle:Json:externalTransfer"}
    options:
        expose: true
tisseo_boa_json_stop_transfer:
    pattern: /json/stop_transfer
    defaults: { _controller: "TisseoBoaBundle:Json:stopTransfer"}
tisseo_boa_json_trip_template:
    pattern: /json/trip_template
    defaults: { _controller: "TisseoBoaBundle:Json:TripTemplate"}

#Stop administration
tisseo_boa_stop_search:
    pattern: /stop/search
    defaults: { _controller: TisseoBoaBundle:Stop:search }
tisseo_boa_stop_edit:
    pattern: /stop/edit/{stopId}
    defaults: { _controller: TisseoBoaBundle:Stop:edit, stopId: null }
tisseo_boa_stop_new:
    pattern: /stop/new/
    defaults: { _controller: TisseoBoaBundle:Stop:new}
tisseo_boa_stop_accessibility_new:
    pattern: /stop_accessibility/new/{stopId}
    defaults: { _controller: TisseoBoaBundle:Stop:newAccessibility, stopId: null}
tisseo_boa_stop_accessibility_delete:
    pattern: /stop_accessibility/delete/{stopId}/{StopAccessibilityId}
    defaults: { _controller: TisseoBoaBundle:Stop:removeStopAccessibility}
tisseo_boa_stop_history_new:
    pattern: /stop_history/new/{stopId}
    defaults: { _controller: TisseoBoaBundle:Stop:newStopHistory, stopId: null}
tisseo_boa_stop_close:
    pattern: /stop/close/{stopId}
    defaults: { _controller: TisseoBoaBundle:Stop:closeStop}
tisseo_boa_stop_history_delete:
    pattern: /stop_history/delete/{stopId}/{StopHistoryId}
    defaults: { _controller: TisseoBoaBundle:Stop:removeStopHistory}

#StopArea administration
tisseo_boa_stop_area_search:
    pattern: /stop_area/search
    defaults: { _controller: TisseoBoaBundle:StopArea:search }
tisseo_boa_stop_area_edit:
    pattern: /stop_area/edit/{stopAreaId}
    defaults: { _controller: TisseoBoaBundle:StopArea:edit, stopAreaId: null }
tisseo_boa_stop_area_alias:
    pattern: /stop_area/edit/alias/{stopAreaId}
    defaults: { _controller: TisseoBoaBundle:StopArea:alias}
tisseo_boa_internal_transfer_edit:
    pattern: /transfer/edit/{stopAreaId}
    defaults: { _controller: TisseoBoaBundle:StopArea:internalTransfer }
tisseo_boa_internal_transfer_save:
    pattern: /transfer/internal/save/{stopAreaId}
    defaults: { _controller: TisseoBoaBundle:StopArea:saveInternalTransfer }
tisseo_boa_external_transfer_save:
    pattern: /transfer/external/save/{stopAreaId}
    defaults: { _controller: TisseoBoaBundle:StopArea:saveExternalTransfer }

tisseo_boa_external_transfer_edit:
    pattern: /external_transfer/edit/{stopAreaId}
    defaults: { _controller: TisseoBoaBundle:StopArea:externalTransfer }

#Route administration
tisseo_boa_line_versions_list:
    pattern: /offers/list
    defaults: { _controller: TisseoBoaBundle:LineVersion:list }
tisseo_boa_route_list:
    pattern: /routes/list/{lineVersionId}
    defaults: { _controller: TisseoBoaBundle:Route:list }
    requirements:
        lineVersionId: \d+
tisseo_boa_route_edit:
    pattern: /routes/edit/{routeId}
    defaults: { _controller: TisseoBoaBundle:Route:edit, routeId: null }
    requirements:
        routeId: \d+
tisseo_boa_route_create:
    pattern: /routes/create/{lineVersionId}
    defaults: { _controller: TisseoBoaBundle:Route:create }
    requirements:
        lineVersionId: \d+
tisseo_boa_route_delete:
    pattern: /routes/delete/{routeId}
    defaults: { _controller: TisseoBoaBundle:Route:delete }
    requirements:
        routeId: \d+
tisseo_boa_route_trip_calendar:
    pattern: /routes/tripcalendars/{lineVersionId}
    defaults: { _controller: TisseoBoaBundle:Route:tripCalendar }
    requirements:
        lineVersionId: \d+
tisseo_boa_route_duplicate:
    pattern: /routes/duplicate/{routeId}
    defaults: { _controller: TisseoBoaBundle:Route:duplicate }
    requirements:
        routeId: \d+

#Trip administration
tisseo_boa_trip_list:
    pattern: /trip/list/{routeId}
    defaults: { _controller: TisseoBoaBundle:Trip:list }
    requirements:
        routeId: \d+
tisseo_boa_trip_edit:
    pattern: /trip/edit/{tripId}
    defaults: { _controller: TisseoBoaBundle:Trip:edit }
    requirements:
        tripId: \d+
tisseo_boa_trip_new:
    pattern: /trip/new/{routeId}
    defaults: { _controller: TisseoBoaBundle:Trip:new }
    requirements:
        routeId: \d+
tisseo_boa_trip_delete:
    pattern: /trip/delete/{tripId}
    defaults: { _controller: TisseoBoaBundle:Trip:delete }
    requirements:
        tripId: \d+
