tisseo_boa_homepage:
    pattern:  /{externalNetworkId}
    defaults: { _controller: TisseoBoaBundle:Default:index , externalNetworkId: null}

#Accessibility administration
tisseo_boa_accessibility_mode_list:
    pattern: /accessibility_mode/list
    defaults: { _controller: TisseoBoaBundle:AccessibilityMode:list }
tisseo_boa_accessibility_mode_edit:
    pattern: /accessibility_mode/edit/{AccessibilityModeId}
    defaults: { _controller: TisseoBoaBundle:AccessibilityMode:edit, AccessibilityModeId: null }

#Agencies administration
tisseo_boa_agency_list:
    pattern: /agency/list
    defaults: { _controller: TisseoBoaBundle:Agency:list }
tisseo_boa_agency_edit:
    pattern: /agency/edit/{AgencyId}
    defaults: { _controller: TisseoBoaBundle:Agency:edit, AgencyId: null }

#Calendars administration
tisseo_boa_calendar_list:
    pattern: /calendar/list/{CalendarType}
    defaults: { _controller: TisseoBoaBundle:Calendar:list, CalendarType: null }
tisseo_boa_calendar_edit:
    pattern: /calendar/edit/{CalendarId}
    defaults: { _controller: TisseoBoaBundle:Calendar:edit, CalendarId: null }
tisseo_boa_calendar_delete:
    pattern:  /calendar/delete/{CalendarId}/{CalendarType}
    defaults: { _controller: TisseoBoaBundle:Calendar:delete}
    

#Calendar elements administration
tisseo_boa_calendar_element_list:
    pattern: /calendar_element/list/{Calendar}
    defaults: { _controller: TisseoBoaBundle:CalendarElement:list, Calendar: null }
tisseo_boa_calendar_element_edit:
    pattern: /calendar_element/edit/{CalendarElementId}
    defaults: { _controller: TisseoBoaBundle:CalendarElement:edit, CalendarId: null }

#Color administration
tisseo_boa_color_list:
    pattern: /color/list
    defaults: { _controller: TisseoBoaBundle:Color:list }
tisseo_boa_color_edit:
    pattern: /color/edit/{ColorId}
    defaults: { _controller: TisseoBoaBundle:Color:edit, ColorId: null }

#Data sources administration
tisseo_boa_datasource_list:
    pattern: /datasource/list
    defaults: { _controller: TisseoBoaBundle:Datasource:list }
tisseo_boa_datasource_edit:
    pattern: /datasource/edit/{DatasourceId}
    defaults: { _controller: TisseoBoaBundle:Datasource:edit, DatasourceId: null }

#Exception types administration
tisseo_boa_exception_type_list:
    pattern: /exception_type/list
    defaults: { _controller: TisseoBoaBundle:ExceptionType:list }
tisseo_boa_exception_type_edit:
    pattern: /exception_type/edit/{ExceptionTypeId}
    defaults: { _controller: TisseoBoaBundle:ExceptionType:edit, ExceptionTypeId: null }

#Log administration
tisseo_boa_log_list:
    pattern: /log/list
    defaults: { _controller: TisseoBoaBundle:Log:list }
tisseo_boa_log_edit:
    pattern: /log/edit/{LogId}
    defaults: { _controller: TisseoBoaBundle:Log:edit, LogId: null }

tisseo_boa_physical_mode_list:
    pattern: /physical_mode/list
    defaults: { _controller: TisseoBoaBundle:PhysicalMode:list }
tisseo_boa_physical_mode_edit:
    pattern: /physical_mode/edit/{PhysicalModeId}
    defaults: { _controller: TisseoBoaBundle:PhysicalMode:edit, PhysicalModeId: null }

tisseo_boa_poi_type_list:
    pattern: /poi_type/list
    defaults: { _controller: TisseoBoaBundle:PoiType:list }
tisseo_boa_poi_type_edit:
    pattern: /poi_type/edit/{PoiTypeId}
    defaults: { _controller: TisseoBoaBundle:PoiType:edit, PoiTypeId: null }
    
tisseo_boa_json_calendars:
    pattern: /json/calendars/{CalendarType}
    defaults: { _controller: "TisseoBoaBundle:Json:calendars", CalendarType: null}   
tisseo_boa_json_bitmask:
    pattern: /json/bitmask
    defaults: { _controller: "TisseoBoaBundle:Json:bitmask"}
tisseo_boa_json_stop:
    pattern: /json/stop
    defaults: { _controller: "TisseoBoaBundle:Json:stop"}
tisseo_boa_json_stop_area:
    pattern: /json/stop_area
    defaults: { _controller: "TisseoBoaBundle:Json:stopArea"}
tisseo_boa_json_city:
    pattern: /json/city
    defaults: { _controller: "TisseoBoaBundle:Json:city"}

#Stop administration
tisseo_boa_stop_search:
    pattern: /stop/search
    defaults: { _controller: TisseoBoaBundle:Stop:search }
tisseo_boa_stop_edit:
    pattern: /stop/edit/{StopId}
    defaults: { _controller: TisseoBoaBundle:Stop:edit, StopId: null }
tisseo_boa_stop_new:
    pattern: /stop/new/
    defaults: { _controller: TisseoBoaBundle:Stop:new}
tisseo_boa_stop_accessibility_new:
    pattern: /stop_accessibility/new/{StopId}
    defaults: { _controller: TisseoBoaBundle:Stop:newAccessibility, StopId: null}
tisseo_boa_stop_accessibility_delete:
    pattern: /stop_accessibility/delete/{StopId}/{StopAccessibilityId}
    defaults: { _controller: TisseoBoaBundle:Stop:removeStopAccessibility}
tisseo_boa_stop_history_new:
    pattern: /stop_history/new/{StopId}
    defaults: { _controller: TisseoBoaBundle:Stop:newStopHistory, StopId: null}    
tisseo_boa_stop_history_delete:
    pattern: /stop_history/delete/{StopId}/{StopHistoryId}
    defaults: { _controller: TisseoBoaBundle:Stop:removeStopHistory}

#StopArea administration
tisseo_boa_stop_area_search:
    pattern: /stop_area/search
    defaults: { _controller: TisseoBoaBundle:StopArea:search }
tisseo_boa_stop_area_edit:
    pattern: /stop_area/edit/{StopAreaId}
    defaults: { _controller: TisseoBoaBundle:StopArea:edit, StopAreaId: null }
tisseo_boa_stop_area_alias:
    pattern: /stop_area/edit/alias/{StopAreaId}
    defaults: { _controller: TisseoBoaBundle:StopArea:alias}
tisseo_boa_transfer_edit:
    pattern: /transfer/edit/{StopAreaId}
    defaults: { _controller: TisseoBoaBundle:StopArea:transfer }
    
#gestion ds Routes
tisseo_boa_linesv_list:
    pattern: /routes/lines/list
    defaults: { _controller: TisseoBoaBundle:Route:list }

#gestion ds Routes
tisseo_boa_route_list:
    pattern: /routes/list
    defaults: { _controller: TisseoBoaBundle:Route:route }

tisseo_boa_route_edit:
    pattern: /routes/edit/{id}
    defaults: { _controller: TisseoBoaBundle:Route:edit }
    requirements:
        id: \d+
    options:
        expose: true/route

tisseo_boa_route_delete:
    pattern: /routes/delete/{id}
    defaults: { _controller: TisseoBoaBundle:Route:delete }
    requirements:
        id: \d+

tisseo_boa_route_create:
    pattern: /routes/create
    defaults: { _controller: TisseoBoaBundle:Route:create }
