services:
    tisseo_boa.ajax_form_listener:
        class: 'CanalTP\SamCoreBundle\EventListener\AjaxFormListener'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    tisseo_boa.type.calendar_selector:
        class: 'Tisseo\BoaBundle\Form\Type\CalendarSelectorType'
        arguments: ['@doctrine.orm.endiv_entity_manager']
        tags:
            - { name: form.type, alias: calendar_selector }
