services:
    sam.business_module.boa:
        class: 'Tisseo\BoaBundle\Permission\BusinessPermissionModule'
        arguments: ['%boa.permissions%']
        public: false
    sam.business_permission_manager.boa:
        class: 'Tisseo\BoaBundle\Permission\BusinessPermissionManager'
        arguments: ['@sam.business_module.boa']
        public: false
    sam.business_perimeter_manager.boa:
        class: 'Tisseo\BoaBundle\Perimeter\BusinessPerimeterManager'
        arguments: ['@nmm.perimeter_manager']
        public: false
    sam.menu_manager.boa:
        class: 'Tisseo\BoaBundle\Menu\MenuManager'
        arguments: ['@service_container']
        public: false
    sam.business_component.boa:
        class: 'Tisseo\BoaBundle\Component\BusinessComponent'
        arguments: ['@sam.business_permission_manager.boa', '@sam.business_perimeter_manager.boa', '@sam.menu_manager.boa']
        public: false
        tags:
            - { name: 'sam.app_business_component', canonical_app_name: 'boa' }

    tisseo_boa.ajax_form_listener:
        class: 'CanalTP\SamCoreBundle\EventListener\AjaxFormListener'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    tisseo_boa.monitoring:
        class: 'Tisseo\BoaBundle\Services\Monitoring'
        arguments:
            - '@tisseo_endiv.line_version_manager'
            - '@tisseo_endiv.calendar_manager'
            - '@tisseo_endiv.stoptime_manager'
            - '@tisseo_endiv.trip_manager'
            - '%tisseo_boa.configuration%'


    tisseo_boa.type.calendar_selector:
        class: 'Tisseo\BoaBundle\Form\Type\CalendarSelectorType'
        arguments: ['@doctrine.orm.endiv_entity_manager']
        tags:
            - { name: form.type, alias: calendar_selector }

    tisseo_boa.type.monitoring.offer_by_line:
        class: 'Tisseo\BoaBundle\Form\Type\OfferByLineType'
        arguments: ['@tisseo_endiv.line_version_manager']
        tags:
            - { name: form.type, alias: boa_offer_by_line_type }
